[versions]
buildconfig = "5.5.1"
dagp = "2.6.1"
# java is referenced from build-logic
java = "17"
junit5 = "5.11.4"
kotlin = "1.9.25"
kotlinEditor = "0.18"
mavenPublish = "0.30.0"
moshi = "1.14.0"
retrofit = "2.9.0"
shadow = "8.3.5"

[libraries]
clikt = "com.github.ajalt.clikt:clikt:4.2.2"
grammar = "com.autonomousapps:gradle-script-grammar:0.5"
kotlinEditor-core = { module = "app.cash.kotlin-editor:core", version.ref = "kotlinEditor" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin"}
okhttp3 = "com.squareup.okhttp3:okhttp:4.9.0"
moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
shadow-gradle-plugin = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
maven-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenPublish" }
slf4j = "org.slf4j:slf4j-simple:2.0.5"

# junit-api, junit-engine, and truth are all referenced from build-logic
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
spock = "org.spockframework:spock-core:2.1-groovy-3.0"
truth = "com.google.truth:truth:1.1.3"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dagp = { id = "com.autonomousapps.dependency-analysis", version.ref = "dagp" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
